# Server configuration
server.port=8085

# Application name
spring.application.name=SpringMvcEmployeeApp

# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML

# Logging
logging.level.com.example.mvc=DEBUG